Test/rest upload part copy
versity/versitygw pull request #1010
Opened 2024-12-31 01:29 UTC by lrm25

2025-01-06 17:42 UTC, anodelman requested changes

2025-01-06 17:42 UTC, anodelman commented on tests/rest_scripts/rest.sh
> +    first_param_added="true"
Having this global var controlled outside the function seems really risky to me - it assumes a 'correct' way to use this and could generate weird bugs when you don't reset it.  Maybe you could parse the url to see what state it is in to correctly add first/additional param?

2025-01-06 21:40 UTC, lrm25 commented on tests/rest_scripts/rest.sh
> +    first_param_added="true"
Yeah, I'll try to fix this

2025-01-07 18:21 UTC, anodelman submitted a review, later dismissed

2025-01-08 17:38 UTC, benmcclelland approved these changes

2025-01-08 17:38 UTC, merged