Test cmdline policy delete tagging
versity/versitygw pull request #739
Opened 2024-08-16 18:22 UTC by lrm25

2024-08-22 17:31 UTC, anodelman requested changes
Please do a pass to remove the if-exit-code-then-return-1 with asserts.

2024-08-26 18:06 UTC, anodelman requested changes
Bunch of exports to pull out.

2024-08-26 18:06 UTC, anodelman commented on tests/commands/get_bucket_tagging.sh
> +  export tags
Unnecessary export.

2024-08-26 18:06 UTC, anodelman commented on tests/commands/get_object_lock_configuration.sh
> +    export get_object_lock_config_err
Unnecessary export.

2024-08-27 18:20 UTC, closed without merging

2024-08-27 18:21 UTC, lrm25 commented
Changes that were supposed to be in this one are now in test_cmdline_policy_delete_tagging_two